### ISSUE TITLE
onMarkerClick

### ISSUE THREAD

**Issue by iceboy1369** [NeshanMaps/android-neshan-maps-sample#2]
با سلام 
آیا رویدادی برای مارک میشود تعریف کرد؟ مثلا وقتی روی مارکر ایجاد شده کلیک کردپیامی نمایش داده شود

**Comment by ahmadazimi** [comment]
در ویکی و سورس کد پروژه استارتر نشان نمونه‌های مختلفی برای این مورد وجود داره:

https://github.com/NeshanMaps/android-neshan-maps-starter/wiki

**Comment by iceboy1369** [comment]
همین؟
چرا هیچی رو جواب نمیدین زورتون میاد؟
اگه من چیزی پیدا میکردم که این همه وقتمو هدر نمیدادم بیام ازتون سوال کنم!

**Comment by raanaYavari** [comment]
https://github.com/NeshanMaps/android-neshan-maps-starter/blob/master/app/src/main/java/org/neshan/sample/starter/activity/AddMarker.java
